### ISSUE TITLE
issues compiling against RHEL 6/CentOS 6 based kernels

### ISSUE THREAD

**Issue by frantechca** [jirislaby/ksplice#1]
Hi,

I'm trying to roll together a patch against the official openvz kernel source (which bases from the RHEL 6 kernel source).

Here is the errors I get reported back:

/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c: In function âapply_updateâ:
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:670: error: implicit declaration of function âref_moduleâ
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c: In function âinit_symbol_arrayâ:
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:989: error: implicit declaration of function âeach_symbol_sectionâ
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c: At top level:
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:3382: error: âset_all_modules_text_roâ undeclared here (not in a function)
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:3382: warning: type defaults to âintâ in declaration of â__ksplice_extract_3382â
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:3383: error: âset_all_modules_text_rwâ undeclared here (not in a function)
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:3383: warning: type defaults to âintâ in declaration of â__ksplice_extract_3383â
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c: In function âstage_storeâ:
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:3388: error: implicit declaration of function âset_all_modules_text_rwâ
/tmp/ksplice-tmp-SwNsuW/kmodsrc/ksplice.c:3406: error: implicit declaration of function âset_all_modules_text_roâ

**Comment by jirislaby** [comment]
Sorry, that is too old kernel to be supported by this package. You need kernel version to be at least 3.0.
