### ISSUE TITLE
CentOS 6

### ISSUE THREAD

**Issue by vanessavasile** [jirislaby/ksplice#4]
Is this supposed to work with CentOS 6?

**Comment by jirislaby** [comment]
Dunno, I have never tried. Try it out...

**Comment by styshoo** [comment]
the kernel version of CentOS 6 is 2.6.*, so ksplice doesn't support it. Ksplice now only support 3.* kernel version.

**Comment by vanessavasile** [comment]
no need to reply to a 2 year old comment. ksplice code was sold to kernelcare and is now only maintained by Oracle for their custom linux.
